### ISSUE TITLE
Circular Dependency in Taxonomy XSD/XML files

### ISSUE THREAD

**Issue by joelebwf** [SunSpecOrangeButton/pyoblib#144]
Jono to supply details in Slack.

**Comment by joelebwf** [comment]
The fields that are circular are:

solar:ProjectAbstract 
solar:ProjectFinancingAbstract
 solar:ProjectLineItems

**Comment by jonoxia** [comment]
Circular dependency is caused by the way data_model.py attempts to construct an "All" entrypoint by combining relationships and concepts from all other entrypoints. This is the wrong way to do it because you get a bunch of redundant relationships.

Instead, have taxonomy_semantic create an "All" entrypoint by reading /core/solar_all_2018-03-31_r01_def.xml and core/solar_all_2018-03-31_r01_pre.xml
