### ISSUE TITLE
Remove hardcoded taxonomy urls

### ISSUE THREAD

**Issue by cwhanse** [SunSpecOrangeButton/pyoblib#170]
Perhaps move the URLs to constants.py as a dict, to collect them in a single place. 
As is, versions of pyoblib are tied to specific releases of the solar (and other) taxonomies.

A possible alternative is to make use of Arelle's taxonomy discovery capabilities.

**Comment by joelebwf** [comment]
I think there is more to this than just moving constants to a single place (although perhaps this is a good start).  We need to also decide what to do when the namespace versions don't line up with the current code - i.e. do we just try to process input and hope for the best or throw an exception?  I will add it to 1.1.0 because this is a reasonable time to address this.
